### ISSUE TITLE
missing control components

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilm_metadata#23]
When considering components, I think you are missing some components that are incorporated in many appliances and radically effect the fingerprints produced by those components, namely the control components. These should be in the components module and built into common combinations for use into components. Some of these may may have built into appliances at a less fundamental level. The main ones are
  * Thermostat - may be paired with heating elements
  * Speed controller - may be paired with motors
  * Dimmer/Rheostat - may be paired with lights or heating elements
  * Timers
There may also be sub classes of these such as
   * discretely variable, i.e. a fixed number of stepped settings (3 fan speed for example)
   * continuously variable, i.e. infinite possible settings such as a lamp dimmer
This would then give you
  * variable  speed motors - such as a washing machine drum motor
  * fixed speed motors - such as pumps
  *  etc

**Comment by JackKelly** [comment]
So, the schema does currently try to capture many of the control options you describe.

`Appliance` has a `control` attribute which can be set to some combination of `{‘timer’, ‘manual’, ‘motion’, ‘sunlight’, ‘thermostat’, ‘always on’}`

Dimmable lights are specified by adding a dimmer component.  e.g. (adapted from Building1 of UK-DALE):

```yaml
- type: light
  subtype: ceiling downlight
  original_name: kitchen_lights
  instance: 1
  meters: [8]
  components:
  - type: LED lamp
    count: 10
    manufacturer: Philips
    model: Dimmable MASTER LED 10W MR16 GU5.3 24degrees 2700K 12v
    nominal_consumption: {on_power: 10}
  - type: dimmer
    subtype: TRIAC
    number_of_dimmer_levels: 3
```

So, the things you suggested which are not yet handled by the schema are:

* Speed controller
* a good generalisation of the distinction between discretely variable and continuously variable.  (dimmers have a `number_of_dimmer_levels` attribute but that idea could probably be generalised).

Also, now that I think about it, perhaps light dimmers should really go into `Appliance:control` rather than `Appliance:components`.  And perhaps `Appliance:control` should really be a list of dicts rather than a list of strings, so we can specify more details of each control object (e.g. whether the controller is continuous or discrete).  What do you think?
